default: Lab2.class Assembler.class Registers.class RegNotFoundException.class

Lab2.class: Lab2.java
	javac Lab2.java
	
Assembler.class: Assembler.java
	javac Assembler.java
	
Registers.class: Registers.java
	javac Registers.java

RegNotFoundException: RegNotFoundException.java
	javac RegNotFoundException.java

clean:
	remove *.class
